## Create Admin
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@user.com",
    "password": "admin",
    "role": "ADMIN"
}

### Create Reader
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{ tokenAdmin }}

{
    "name": "Reader",
    "email": "reader@user.com",
    "password": "reader",
    "role": "READER"
}

### Create Writer
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{ tokenAdmin }}

{
    "name": "Writer",
    "email": "writer@user.com",
    "password": "writer",
    "role": "WRITER",
    "permissions": [
        {
            "action": "read",
            "resource": "User"
        }
    ]
}

### 
GET http://localhost:3000/users
Authorization: Bearer {{ tokenAdmin }}
###
GET http://localhost:3000/users/cmp69eq140000s8zb2ninfeoo

# jwt.io
###
# @name adminLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}

###
@tokenAdmin = {{ adminLogin.response.body.access_token }}

# @name readerLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "reader@user.com",
    "password": "reader"
}

###
@tokenReader = {{ readerLogin.response.body.access_token }}

###
# @name writerLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "writer@user.com",
    "password": "writer"
}

###
@tokenWriter = {{ writerLogin.response.body.access_token }}

###
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{ tokenAdmin }}
# Authorization: Bearer {{ tokenReader }}

# "published": true
{
    "title": "First Post",
    "content": "This is the content of the first post.",
    "published": false
}

###
GET http://localhost:3000/posts
Authorization: Bearer {{ tokenAdmin }}
# Authorization: Bearer {{ tokenReader }}

###
GET http://localhost:3000/cmpvyivb7000084zbx13epyt1
Authorization: Bearer {{ tokenReader }}

###
GET http://localhost:3000/users
# Authorization: Bearer {{ tokenAdmin }}
# Authorization: Bearer {{ tokenWriter }}
Authorization: Bearer {{ tokenReader }}