POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@user.com",
    "password": "admin",
    "role": "ADMIN"
}

### 
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwicm9sZSI6IkFETUlOIiwic3ViIjoiY21wNjllcTE0MDAwMHM4emIybmluZmVvbyIsImlhdCI6MTc3ODk0MjM1MiwiZXhwIjoxNzc4OTQ5NTUyfQ.Uj3oxa2Nlqjlf9pt_NybOoRjcoqTiLqy2nY7qnDy53U
###
GET http://localhost:3000/users/cmp69eq140000s8zb2ninfeoo

# jwt.io
###
# @name adminLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}

###
@tokenAdmin = {{ adminLogin.response.body.access_token }}

###
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{ tokenAdmin }}

{
    "title": "First Post",
    "content": "This is the content of the first post.",
    "published": true
}